# Copyright (C) 2026  Henrique Almeida
# This file is part of X11 Wayland Dev.
#
# X11 Wayland Dev is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# X11 Wayland Dev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with X11 Wayland Dev.  If not, see <https://www.gnu.org/licenses/>.

name: Update Docker Hub Description

on:
  push:
    branches:
      - "main"
    paths:
      - "README.md"
      - ".github/workflows/dockerhub-description.yml"

jobs:
  update-desc:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Run peter-evans/dockerhub-description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
